name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      run: sudo apt-get install -y cmake

    - name: Set up SDL2
      run: sudo apt-get install -y libsdl2-dev

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Build artifacts for ${{ github.ref }}
      timeout-minutes: 10

    - name: Upload Build Artifacts
      id: upload_artifacts
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/my_application
        asset_name: my_application
        asset_content_type: application/octet-stream
